"""pk_second

Revision ID: 172c1592b7a8
Revises: 996b9c783bd6
Create Date: 2023-11-19 00:24:54.227154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172c1592b7a8'
down_revision = '996b9c783bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pk_unique', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pk_unique', type_='unique')
    # ### end Alembic commands ###
