"""populate_existing

Revision ID: ad0c130fee09
Revises: 6cf019aba890
Create Date: 2023-11-20 23:23:42.136062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0c130fee09'
down_revision = '6cf019aba890'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('populate_existing_storage',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('populate_existing_storage')
    # ### end Alembic commands ###
